In [2]:
import numpy as np
import pandas as pd

### numpy

In [3]:
x1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x2d = np.array([ x1d,  x1d + 1,  x1d + 2,  x1d + 3, x1d + 4 ])

In [4]:
x2d[:, :6] >  4

array([[False, False, False, False, False,  True],
       [False, False, False, False,  True,  True],
       [False, False, False,  True,  True,  True],
       [False, False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True,  True]], dtype=bool)

### copy

In [5]:
tmp = x2d[:, :8].copy()
#criar variável nova (usar copy) se não quiser modificar valor na variável original quando fizer um slice

In [6]:
tmp[tmp >  6] = 13
tmp[tmp <  2] = -13
print(tmp)

[[-13 -13   2   3   4   5   6  13]
 [-13   2   3   4   5   6  13  13]
 [  2   3   4   5   6  13  13  13]
 [  3   4   5   6  13  13  13  13]
 [  4   5   6  13  13  13  13  13]]


In [7]:
tmp[(tmp == -13) | (tmp == 13)] = 0
print(tmp)

[[0 0 2 3 4 5 6 0]
 [0 2 3 4 5 6 0 0]
 [2 3 4 5 6 0 0 0]
 [3 4 5 6 0 0 0 0]
 [4 5 6 0 0 0 0 0]]


In [8]:
tmp[(tmp > 0) & (tmp < 6)] = -3
print(tmp)

[[ 0  0 -3 -3 -3 -3  6  0]
 [ 0 -3 -3 -3 -3  6  0  0]
 [-3 -3 -3 -3  6  0  0  0]
 [-3 -3 -3  6  0  0  0  0]
 [-3 -3  6  0  0  0  0  0]]


### pandas

In [13]:
index = pd.Index(data=["Leite", "Ovos", "Carne", "Arroz", "Feijão"], name="Itens")
sq = pd.Series(index=index,  data=[2, 12, 1, 5, 2]).sort_values()
sq

Itens
Carne      1
Leite      2
Feijão     2
Arroz      5
Ovos      12
dtype: int64

In [14]:
#atribuição de valores em uma cópia
s_tmp = sq.copy()

In [15]:
s_tmp[s_tmp == 2]

Itens
Leite     2
Feijão    2
dtype: int64

In [17]:
s_tmp[s_tmp == 2] = 3
s_tmp

Itens
Carne      1
Leite      3
Feijão     3
Arroz      5
Ovos      12
dtype: int64

In [18]:
index = ["Leite", "Ovos", "Carne", "Arroz", "Feijão"]
df = pd.DataFrame(
    [
        pd.Series(name="Quantidade", index=index,  data=[2, 12, 1, 5, 2]),
        pd.Series(name="Unidade", index=index,  data=["L", "Ud", "Kg", "Kg", "Kg"])
    ]
)
df = df.T
df["Preço p/ Ud"] = [5.00, 29.99, 6.50, 3.30, 0.50]
df["Preço Total"] = [25.00, 29.99, 13.00, 6.60, 6.00]
df

Quantidade Unidade  Preço p/ Ud  Preço Total
Leite           2       L         5.00        25.00
Ovos           12      Ud        29.99        29.99
Carne           1      Kg         6.50        13.00
Arroz           5      Kg         3.30         6.60
Feijão          2      Kg         0.50         6.00

In [19]:
#atribuir valores em 'slices' levanta warnings
#deve-se usar 'loc' ou 'iloc'
df.loc["Carne", "Unidade"] = "Kilograma"
df.iloc[3, 1] = "Litro"
df

Quantidade    Unidade  Preço p/ Ud  Preço Total
Leite           2          L         5.00        25.00
Ovos           12         Ud        29.99        29.99
Carne           1  Kilograma         6.50        13.00
Arroz           5      Litro         3.30         6.60
Feijão          2         Kg         0.50         6.00

In [20]:
#atribuição de valores em uma cópia
df_tmp = df[["Preço p/ Ud", "Preço Total"]].copy()
df_tmp

Preço p/ Ud  Preço Total
Leite          5.00        25.00
Ovos          29.99        29.99
Carne          6.50        13.00
Arroz          3.30         6.60
Feijão         0.50         6.00

In [21]:
mask = (df_tmp > 5) & (df_tmp < 10)
mask

Preço p/ Ud  Preço Total
Leite         False        False
Ovos          False        False
Carne          True        False
Arroz         False         True
Feijão        False         True

In [22]:
df_tmp[mask]

Preço p/ Ud  Preço Total
Leite           NaN          NaN
Ovos            NaN          NaN
Carne           6.5          NaN
Arroz           NaN          6.6
Feijão          NaN          6.0

In [23]:
tmp2 = df_tmp.copy()
tmp2[mask] = "?"
tmp2

Preço p/ Ud Preço Total
Leite            5          25
Ovos         29.99       29.99
Carne            ?          13
Arroz          3.3           ?
Feijão         0.5           ?

### filtering with masks

In [ ]:
brics["area"] > 8
is_huge = brics["area"] > 8
brics[is_huge]

In [ ]:
between = np.logical_and(brics["area"] > 8, brics["area"] < 10)